main.cpp, makefile, ppcemumain.h, ppcfpopcodes.cpp, ppcmemory.cpp, ppcopcodes.cpp, viacuda.cpp
Summary:
* Makefile: 'main.c' has been corrected to 'main.cpp'
* Makefile: -std=c++11 need to be explicitly added to the compilation options to work with GCC 4.x
* Using "&&" where bitwise AND is required triggers compilation warnings when compiling with non-M$oft compilers. Fixed by the proper replacement.
=> Various fixes and improvements for non-Windows systems.

CMakeLists.txt, debugger.cpp, debugger.h, main.cpp, makefile, ppcmemory.cpp, ppcopcodes.cpp
This PR adds a simple command-line debugger. It can be invoked like that:
`./dingusppc debugger`
Moreover, I fixed the following stuff:
* mask generation for rotation instructions (rlwinm, rlwimi, rlwnm)
* XER[CA] updates for addc, adde & subfic
* mfmsr emulation
These fixes are enough to pass the PowerMac 6100 ROM checksum validation.
Please note that carry update logic after `adde` has been taken from http://tomoyo.osdn.jp/cgi-bin/lxr/source/arch/powerpc/lib/sstep.c?v=linux-4.12.14#L1113
Unfortunately, it does't match the MAME debugger. The question is which one - Linux code or MAME debugger - is wrong. I don't know.
Carry updates after `subfze` and perhaps some other arithmetic instructions are wrong and need to be carefully checked and fixed...
=> Various CPU emulation fixes + new command-line debugger.

ppcfpopcodes.cpp
That fixes Clang warnings on macOS.
=> ppcfpopcodes: replace logical AND with AND where required.

main.cpp, ppcemumain.h, ppcmemory.cpp, ppcopcodes.cpp
As the title says, I replaced three maps with arrays of function pointers. They all are now resided in the source file where they are used. Keeping static tables in header files should be avoided.
=> Map->Array replacements.

.gitignore, CMakeLists.txt, devices/dbdma.cpp, devices/i2c.h
- Fix missing includes for `std::memcpy` and `std::memset` in `devices/dbdma.cpp` and `devices/i2c.h` on linux.
- Fix build due to `libdl` not being linked.
Note: `libsoundio` is building and linking fine without any changes on linux
=> Fix build on linux

devices/common/pci/bandit.cpp, devices/memctrl/mpc106.cpp
PCI config read fails should return all 1 bits.
All unused registers in an existing PCI device should return 0.
Because that's what my Power Mac 8600 returns when I run my Open Firmware lspci command.
Any bus/device/function that doesn't exist returns FF and won't be listed by lspci.
Any registers that are unused will show as 00 in the lspci output.
Make grackle log bus:device.function @register.size in all cases.
=> Fix return value for bad pci config address

core/mathutils.h, cpu/ppc/ppcemu.h, cpu/ppc/ppcexec.cpp, cpu/ppc/ppcopcodes.cpp
1)
Fixed a typo that caused rtc@ to always return 0 for the upper 32 bits (represents seconds). The problem could cause the following to hang on Power Mac 7500:
`cr 2000 0 do get-msecs u. 1 ms loop`
2)
Fixed an issue where the following would cause inconsistent results (tb in the left column would sometimes decrement instead of increment):
```
: tbrtctest
2 0 do
2 0 do
cr tb@ 8 u.r ." ." 8 u.r
loop
2 0 do
cr 12 spaces rtc@ 8 u.r ." ." 8 u.r
loop
2 0 do
cr tb@ 8 u.r ." ." 8 u.r space
rtc@ 8 u.r ." ." 8 u.r
loop
loop
;
tbrtctest
```
RTC and TBR could not be used simultaneously because they are both incremented by an amount based on the last time stamp but that time stamp can be changed by accessing either RTC or TBR. The solution is to have a different time stamp for each.
3)
Fixed an issue …
=> RTC and TBR fixes

devices/common/pci/pcidevice.cpp
The Pointer to PCI Data Structure is supposed to be two bytes. It is described in the PCI Firmware Specification Revision 3.0, section 5.1.1. PCI Expansion ROM Header Format. The pointer is two bytes at 0x18. The pointer is supposed to be a multiple of 4 which means there's always at least two bytes of padding after the pointer. Some BIOS firmware images may use the 2 bytes following the pointer for other purposes (plus additional bytes before the PCI Data Structure) so we cannot assume the bytes will be zero. Some PCI expansion ROMs may include both BIOS and Open Firmware images.
=> Fix PCI struct offset size

devices/common/pci/bandit.cpp, devices/common/pci/bandit.h, devices/common/pci/pcidevice.cpp, devices/common/pci/pcidevice.h, devices/ioctrl/grandcentral.cpp, devices/ioctrl/heathrow.cpp, devices/ioctrl/ohare.cpp, devices/memctrl/mpc106.cpp, devices/video/atimach64gx.cpp, devices/video/atirage.cpp, devices/video/control.cpp
While dingusppc only emulates 32-bit Macs (for now), it is possible for a 32-bit Power Mac to use a PCIe card that has 64-bit BARs.
finish_config_bars is added to scan the cfg values of the BARs and determine their type. The type is stored separately so that it does not need to be determined again.
The type can be I/O (16 or 32 bit) or Mem (20 or 32 or 64 bit). A 64 bit bar is two BARs, the second contains the most significant 32 bits.
set_bar_value uses the stored type instead of trying to determine the type itself. It is always called even when the firmware is doing sizing. For sizing, It does the job of setting the bar value so do_bar_sizing is now just a stub.
Every PCIDevice that has a BAR needs to call finish_config_bars after setting up the cfg values just as they need to setup the …
=> 64 bit BAR support

devices/common/pci/bandit.cpp, devices/common/pci/bandit.h, devices/common/pci/pcibridge.cpp, devices/common/pci/pcibridge.h, devices/common/pci/pcidevice.cpp, devices/common/pci/pcidevice.h, devices/common/pci/pcihost.cpp, devices/common/pci/pcihost.h, devices/memctrl/mpc106.cpp, devices/memctrl/mpc106.h, devices/video/atirage.cpp, devices/video/atirage.h, machines/machinecatalyst.cpp, machines/machinegazelle.cpp, machines/machinegossamer.cpp, machines/machinetnt.cpp, zdocs/grackle.md
Add PCI bridge and multi-function device support.
Overview:
- A multi-function device is two or more PCIDevices with the same device number but one device is function zero (as with currently implemented PCIDevices) and the other functions have function numbers between 1 and 7. The device number and function number are properties of the PCIDevice's parent PCIHost connection.
- A PCIBridge is a PCIHost (it can connect child PCI devices) and a PCIDevice (it has config space, BARs, and expansion ROM).
- A PCIDevice has Type 0 header. It has 6 BARs.
- A PCIBridge has Type 1 header. It has 2 BARs. The config space registers beginning from offset 0x18 differ from those of a PCIDevice.
Possible future modifications:
- Add a PCICardBus class. It is a PCIHost. It has Type 2 header. It has one BAR. …
=> Pci bridge and multi function support

core/hostevents_sdl.cpp, devices/common/adb/adbbus.cpp, devices/common/adb/adbbus.h, devices/common/adb/adbdevice.cpp, devices/common/adb/adbdevice.h, devices/common/adb/adbkeyboard.cpp, devices/common/adb/adbkeyboard.h, devices/common/viacuda.cpp
Besides generating `KeyboardEvent`s in the SDL event handler and returning the key state in the register 0 reads of the `AdbKeyboard` device, we also needed to generalize the ADB bus polling a bit. We now check all devices that have the service request bit set, instead of hardcoding the mouse.
The SDL key event -> ADB raw key code mapping is based on BasiliskII/ SheepShaver's, but cleaned up a bit.
To test this, I've been using the PDM ROM with a slightly tweaked [7.1.2 Disk Tools image](https://github.com/mihaip/infinite-mac/raw/main/Images/System%207.1.2%20Disk%20Tools%20FD.dsk?download=) that has the Key Caps DA installed.
=> Implement the ADB keyboard

CMakeLists.txt, main_sdl.m
As part of adding ADB keyboard support (#56), we're now running into conflicts between the guest and host OS keyboard shortcuts when running on macOS hosts.
SDL2 unconditionally adds some menu items to the "Window" menu, and there are built-in ones too. As a workaround, we now iterate over all menu items are swap out command for control, since the the latter is generally unused in classic Mac OS.
=> Remap Cocoa/macOS menu item key modifiers

devices/common/ata/atahd.cpp, devices/common/scsi/scsicdrom.cpp, devices/common/scsi/scsicdrom.h, devices/common/scsi/scsihd.cpp, devices/common/scsi/scsihd.h, devices/floppy/floppyimg.cpp, devices/storage/blockstoragedevice.cpp, devices/storage/blockstoragedevice.h, utils/CMakeLists.txt, utils/imgfile.h, utils/imgfile_sdl.cpp
Allows different implementations for different platforms (the JS build relies on browser APIs to stream disk images over the network).
Setting aside the JS build, this also reduces some code duplication.
=> Move disk image reading to be behind an ImgFile class

devices/common/adb/adbkeyboard.cpp
We were using an empty value on the second byte of the ADB keyboard register 0, but that maps to the "a" key. This manifested itself as the Key Caps DA never showing the "a" key as being down.
Switch to a non-existent key for the second byte.
=> Fix "a" key always being as as a keyup

cpu/ppc/poweropcodes.cpp
doz and dozi were storing the result into the wrong register.
nabs was not taking into account two's complement storage of numbers and was just setting the signed bit.
These two instructions are used in the implementation of text measurement in native QuickDraw on 7.1.2/the PDM ROM, and the incorrect values were resulting in nothing being rendered. With the fix text appears when booting from the 7.1.2 CD.
=> Fix emulation of doz, dozi, and nabs POWER instructions

cpu/ppc/ppcexec.cpp, cpu/ppc/ppcopcodes.cpp
The `SubOpcode31Grabber[1024] = { ppc_illegalop }` initializer only populates the first entry with ppc_illegalop (at least on some compilers), switch to explicitly initializing the entire array with `std::fill_n`.
Also fix a couple of sign and overflow issues flagged by the Xcode undefined behavior sanitizer.
=> Avoid some undefined behavior

devices/common/scsi/scsihd.cpp
The call to the `ScsiDevice` superclass was using the `name` field (which was not initialized yet) instead of the `name` constructor argument.
=> Fix uninitialized value read in the ScsiHardDisk constructor

devices/common/adb/adbmouse.cpp, devices/common/adb/adbmouse.h
We now respond to the switch to device handler ID 4 and the register 1 read (as described by https://developer.apple.com/library/archive/technotes/hw/hw_01.html#Extended).
We don't yet use the extra precision bits in the register 0.
=> Add basic support for the extended ADB mouse protocol.

main_sdl.m
Adds a "Grab Mouse" command to the "Window" menu which toggles `SDL_SetRelativeMouseMode`. That "traps" the mouse to the current window (and hides it) which makes it less annoying to deal with the separate acceleration curves of the host and guest OS.
This needs to be done via AppKit code since SDL does not have a cross-platform way to add menu commands.
I also looked into the extended ADB mouse protocol but it does not appear to do that we want. If we use it to report a device class of `classAbsolute` (0) the acceleration curve changes to a flat response (we end up using `accl` 0 from https://github.com/elliotnunn/supermario/blob/9dd3c4bef84df2ea30f5ec2c5e97b043e8267b3f/base/SuperMarioProj.1994-02-09/Resources/MiscROMRsrcs.r#L64-L76) but the coordinates are still interpreted as being …
=> Add a basic mouse grab mode when running on macOS

devices/common/machineid.h, machines/machinepdm.cpp
Handle 4 byte reads from the machine ID MMIO region. Also change the 6100 machine ID to match the one used by MAME.
=> machinepdm: fix machine ID

core/coresignal.h, core/hostevents.h, cpu/ppc/ppcemu.h, cpu/ppc/ppcmmu.cpp, debugger/debugger.cpp, devices/common/viacuda.cpp, devices/common/viacuda.h, devices/ioctrl/amic.cpp, devices/ioctrl/amic.h, devices/video/videoctrl.cpp, main.cpp
There are cases where when it's necessary (e.g. given uninitialized NVRAM, the Beige G3 with the 10.2 install CD inserted will update the boot device and restart to boot from it).
Restart support was done by wrapping the `ppc_exec` function in a loop. This uncovered some cases where we were not fully tearing down state (removal of refresh intervals) or resetting it (MMU regions), but with those fixed, we are able to boot the 10.2 install CD to the spinner from an empty state.
=> Add support for the CUDA_RESTART_SYSTEM command

main.cpp
The `SIGABRT` handler is not invoked by the abort() call in the loguru fatal handler, but either way it's not necessary (it does its own `abort()`).
Switch to explicitly cleaning up the machine object, which as a side effect in the destructor chain will persist the NVRAM.
=> Ensure that NVRAM is persisted when exiting the debugger after an abort

devices/common/pci/bandit.cpp
Refactor from e7da98b6bddbce0208d890ba23ed55d07d05b119 accidentally made the non-Aspen PCI code path for `CONFIG_ADDR` writes by a no-op.
=> bandit: Fix regression in non-Aspen PCI bridge

.github/workflows/cmake.yml
This GitHub Actions workflow automates the build process for DingusPPC, generating binaries for both Windows and Linux platforms. Upon completion, the script seamlessly uploads the compiled binaries to artifacts, simplifying distribution.
The script currently supports five build modes:
**Normal Linux Builds**: This mode compiles the Linux binaries and uploads them to artifacts.
**MSYS2**: Included for testing purposes, this mode always shows as successful and is intended for potential future use in fixing MSYS2 builds.
**vsbuild Clang**: Compiles the project using the Clang compiler in Visual Studio 2022 and uploads the resulting binaries.
**vsbuild MSVC**: Similar to the above mode but uses the MSVC compiler, useful for debugging purposes.
**vsbuild MSVC MSBuild**: Another test mode to …
=> Enhanced GitHub Actions Workflow for DingusPPC Build Automation 

cpu/ppc/ppcexec.cpp, main.cpp, utils/profiler.cpp, utils/profiler.h
Keeps track of instructions (including operands) that are executed, to see if there are any hotspots that could be optimized or fastpaths that should be added.
Also adds a mode where CPU profiler data is periodically output, to make it easier to get at these instruction counts during startup.
=> Add instruction counters to CPU profiler

cpu/ppc/ppcdisasm.cpp, devices/memctrl/mpc106.cpp
Had issues compiling this with GCC 14.1.1 (20240618) on `ppc64le`.
Adding two includes fixed it however.
=> Fix missing std::find_if and others with GCC 14.1.1

core/hostevents_sdl.cpp
I found this bug while trying to figure out why dingus won't work when compiled with MSVC (I still had to use Clang when compiling w/ vs2022).
Basically when the keyboard is in a specific state (NumLock, CapsLock, etc.) the code below:
```
if ( event.key.keysym.sym == SDLK_g && SDL_GetModState() == KMOD_LCTRL) {
if (event.type == SDL_KEYUP) {
toggle_mouse_grab(event.key);
}
return;
}
```
doesn't work because since if the keyboard is in a specific state, it returns the OR'd combination of said modifier, in this case CTRL, which has a value of 0x40, with the state of the keyboard.
So if the keyboard has all locks disabled, `SDL_GetModState()` returns the value of 0 | 0x40. But if NumLock is enabled, it returns the value of `0x1000 | 0x40` or `0x2000 | 0x40` if caps lock is enabled, meaning …
=> Fix keyboard event bug where mouse grab combination won't work if SDL_GetModState

core/hostevents_sdl.cpp
The initial change I committed worked fine before.
=> Do not test for equality when checking if ctrl is pressed.

utils/imgfile.h, utils/imgfile_sdl.cpp
`size_t` and `off_t` are 32-bit values in Emscripten, which causes issues with disk images larger than 4GB. Use the explicit type (which is more consistent with the rest of the codebase anyway).
=> Switch ImgFile to using uint64_t explicitly

devices/video/atimach64gx.cpp, devices/video/atirage.cpp, devices/video/display.h, devices/video/display_sdl.cpp, devices/video/videoctrl.cpp, devices/video/videoctrl.h
The JS implementation does content hashing to not blit unchanged framebuffer contents (see mihaip/dingusppc@171ff2d40788b9316274505fb2c9ac0990f85c47). However, that is not necessary for the ATI adapters that already track this and only set `draw_fb` if the framebuffer has actually changed.
Pass through a `fb_known_to_be_changed` for these cases, and also add an optional `update_skipped` method (since the JS still wants to know when the last logical screen update was).
=> Pass through draw_fb optimization metadata to Display class

cpu/ppc/ppcopcodes.cpp, devices/memctrl/memctrlbase.cpp
They happen surprisingly often, and flushing the TLB is expensive because we need to walk over all entries.
Takes booting 10.2 on a Beige G3 from binary start to "Welcome to Macintosh" from 58s to 38s on my machine.
Also includes a small performance optimization for scanning address ranges on TLB cache misses.
=> ppcopcodes: avoid TLB flushes for noop SR changes

devices/common/adb/adbmouse.cpp
Fixes any mouse driver that only supports the classic protocol and expects register 0 reads to return two bytes.
=> adbmouse: only send first two bytes in standard/classic protocol as per spec

devices/video/display_sdl.cpp
without this, SDL window can act like a "hang" window unless there is update(s) from emulated context.
=> sdl: handle SDL_WINDOWEVENT_EXPOSED event to fix redrawing issue

cpu/ppc/ppcmmu.cpp
Mode 1 contains real addressing mode entries, which by definition cannot be using segment registers. By skipping over them, we can shave off a couple of seconds from the 10.2 boot time.
=> ppcmmu: skip over mode 1 entries when doing PAT flushes

devices/common/ata/atabasedevice.h, devices/common/ata/atapibasedevice.h
Both `cmd_pkt` and `data_buf` class members are cast to a `uint16_t` pointer, so we need to make sure they are properly aligned, otherwise it is undefined behavior.
=> atapibasedevice: fix unaligned memory access

cpu/ppc/poweropcodes.cpp, cpu/ppc/ppcemu.h, cpu/ppc/ppcexec.cpp, cpu/ppc/ppcfpopcodes.cpp, cpu/ppc/ppcopcodes.cpp
There's no reason for it to be a global, we always set it and use it in instruction implementations, and we never read it directly.
Perhaps the compiler could optimize this away, but it's better to be simpler (and also be easier to read).
=> ppc: make ppc_effective_address into a local

devices/common/ata/atahd.cpp, devices/common/ata/atahd.h
1f2256ec81a and 7ee8b9b2f were referencing a `multiple_sector_count` field, but it was never set. This was resulting in an error being returned (`READ MULTIPLE with SET MULTIPLE==0`). We actually should use `sec_per_block`, which bd16b7c69ee27 introduced.
=> Fix ATA HD initialization on Beige G3 when booting 9.2

devices/common/ata/atabasedevice.cpp, devices/common/ata/atahd.cpp, devices/common/ata/atahd.h
We may be transferring less data than can fit in a chunk, so we need to ensure that `xfer_cnt` is clamped to 0 when transferring the last chunk (otherwise it remains negative, and `has_data()` will return true).
It's also possible that the transfer size is bigger than a chunk but not an even multiple of the chunk size, so we need to ensure that we don't try to transfer a whole chunk in the last iteration.
More correctly initialize the device identification struct, to report the maximum (word 47) and current (word 59) number of blocks that can be transferred with `READ_MULTIPLE` and `WRITE_MULTIPLE` commands.
Fix `post_xfer_action` to write the actual chunk size that was written, as opposed to an entire chunk (which may be larger).
=> Fixes for READ_MULTIPLE and WRITE_MULTIPLE commands

core/hostevents.h, core/hostevents_sdl.cpp, devices/video/display_sdl.cpp
Avoids blurriness on macOS hosts with Retina displays.
| Before | After |
|--------|--------|
| <img width="1136" alt="image" src="https://github.com/user-attachments/assets/99631a45-44ec-42dd-9ca4-c71032b04422"> | <img width="1136" alt="image" src="https://github.com/user-attachments/assets/066054fa-f862-4ec0-8667-f96175d7d47f"> |
=> Enable HiDPI mode for SDL and ensure that we use nearest-neighbor scaling

core/coresignal.h, core/hostevents.h, core/timermanager.h, cpu/ppc/ppcemu.h, cpu/ppc/ppcexec.cpp, devices/common/nvram.cpp, devices/common/viacuda.cpp, devices/sound/awacs.cpp, devices/sound/soundserver.h, devices/sound/soundserver_cubeb.cpp, main.cpp, utils/imgfile_sdl.cpp
Adds support for a `--deterministic` command-line option that makes repeated runs the same:
- Keyboard and mouse input is ignored
- The sound server does a periodic pull from the DMA channel (so that it gets drained), but only does so via a periodic timer (instead of being driven by a cubeb callback, which could arrive at different times)
- Disk image writes are disabled (reads of a modified area still work via an in-memory copy)
- NVRAM writes are disabled
- The current time that `ViaCuda` initializes the guest OS is always the same.
This makes execution exactly the same each time, which should make debugging of more subtle issues easier.
To validate that the deterministic mode is working, I've added a periodic log of the current "time" (measured in cycle count), PC and opcode. When …
=> Add a deterministic execution mode

devices/common/pci/pcihost.cpp, machines/machinefactory.cpp, machines/machinefactory.h, main.cpp
The previous approach of traversing the machine and its device tree at startup to register CLI11 options was not working for dynamically registered devices like PCI cards. This meant that options like `gfxmem_size` or `mon_id` from the video cards could not be set.
Switch to instead registering in `MachineFactory` a hook function that provides CLI flag values. We can call it when registering any property, whether at startup or dynamically.
=> Add support for specifying properties of dynamically-registered devices via the command line

utils/CMakeLists.txt, utils/imgfile_sdl.cpp
Before f65f9b9845ddf0a4050213cc36ef43c9c852a6c7 this would happen automatically (since the `stream` member was always valid). It's now a `unique_ptr` that's only initialized when the file is opened, so we need to add guards for all the operations.
=> Make ImgFile ignore operations before the file is opened

cpu/ppc/ppcemu.h, cpu/ppc/ppcexec.cpp, cpu/ppc/test/ppctests.cpp, utils/imgfile_sdl.cpp
Instead of a primary opcode lookup table with 64 entries and a few smaller tables with 4-2048 entries, use a single 64 * 2048 (128K) entry table to dispatch opcodes.
Helps with performance, since we avoid the function call overhead for some frequently-used instructions (e.g. branch, integer, floating point). Saves ~2 seconds from the time to Welcome to Macintosh (same measurement methodology as #125)
Secondarily also makes opcode registration/decoding a bit more uniform, and scannable, since it's now all in `initialize_ppc_opcode_table`.
=> ppc: Use a unified opcode lookup table

devices/common/adb/adbbus.cpp, devices/common/pci/bandit.cpp, devices/deviceregistry.cpp, devices/deviceregistry.h, devices/ioctrl/amic.cpp, devices/ioctrl/grandcentral.cpp, devices/ioctrl/ohare.cpp, devices/memctrl/platinum.cpp, devices/serial/escc.cpp, devices/video/atimach64gx.cpp, devices/video/atirage.cpp, devices/video/control.cpp, machines/machinecatalyst.cpp, machines/machinefactory.h, machines/machinegazelle.cpp, machines/machinegossamer.cpp, machines/machinepdm.cpp, machines/machinepippin.cpp, machines/machineproperties.cpp, machines/machineproperties.h, machines/machinetnt.cpp, machines/machineyosemite.cpp
It's somewhat of an anti-pattern, and can lead to conflicts with other symbols (e.g. the Windows build failure in https://github.com/dingusdev/dingusppc/actions/runs/11762906342/job/32766290288, I removed `using namespace std` from timermanager.h to fix that one).
=> Remove `using namespace std` from remaining header files

cpu/ppc/ppcemu.h, cpu/ppc/ppcexceptions.cpp, cpu/ppc/ppcexec.cpp, cpu/ppc/ppcopcodes.cpp
Rather than running them normally, they should trigger a "no FPU" exception. This appears to be required to allow correct graphical rendering under Mac OS X - the FP bit cleared via `mtmsr` and `rfi` instructions and something else appears to be relying on the exception to be thrown.
Implemented by maintaining a parallel version of the `OpcodeGrabber` table (`OpcodeGrabberNoFPU`) which contains alternate implementations for all the floating point instructions. We switch the table whenever the MSR value changes. This should minimize the overhead of doing these checks.
=> Respect FP bit in MSR when running floating point instructions

cpu/ppc/ppcemu.h, cpu/ppc/ppcexceptions.cpp, cpu/ppc/ppcexec.cpp, cpu/ppc/ppcopcodes.cpp, cpu/ppc/test/ppctests.cpp
In #135 we switched from a static `OpcodeGrabber` table to a `curOpcodeGrabber` pointer in `ppc_main_opcode`. This results in an extra indirection (as far as generated assembly having an additional load), which reduces execution speed.
Switch to making the opcode grabber into a parameter to `ppc_main_opcode`, and make `ppc_exec_inner` keep it up to date (via an `EXEF_OPCODE` exception flag). 
Also fixes FPU instructions in `ppctests` - we now need to set the FP MSR bit when initializing the CPU.
=> Mitigate performance impact of respecting FP bit
